[package]
name = "chessbik"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "*"
bevy_mod_picking = { path = "./bevy_mod_picking" } # remove keyboard interaction [src/selection.rs]
bevy-inspector-egui = "*"
bevy_stl = "*"
bevy-orbit-controls = { path = "./bevy-orbit-controls" } # upgrade bevy dep to 0.7 [Cargo.toml]
lazy_static = "*"
derive_more = "*"
actix-web = "*"
actix-cors = "*"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "latest", version = "=0.7.0" }

[profile.release]
opt-level = 3

[profile.release.package."*"]
opt-level = 3
